version: "3.8"

services:
  mongo:
    image: mongo:6
    container_name: lead-scoring-mongo
    ports:
      - "27017:27017"

  redis:
    image: redis:7
    container_name: lead-scoring-redis
    ports:
      - "6379:6379"
